import { ConversationItem } from "./types";

export const initialMockConversations: ConversationItem[] = [
  {
    id: "conv-4a8c",
    visitor: {
      id: "vis-4a8c",
      name: "Visitor 4a8c",
      handle: "Visitor 4a8c",
      avatarSeed: "4a8c",
      avatarExpression: "heart",
      isOnline: true,
      email: "elena.v@acme-corp.de",
      location: "Unknown location",
      localTime: "12:27 local time",
      language: "American English",
      device: "Desktop",
      browser: "Chrome",
      os: "Mac OS",
      currentPage: "localhost:3000",
      cameFrom: "Direct visit",
      firstSeen: "6 minutes ago",
      lastSeen: "6 minutes ago",
      visitsCount: 1,
    },
    status: "WAITING_HUMAN",
    handoffReason: "The visitor asked for a person",
    lastMessageSnippet: "Go to acme.example/login and click Forgot...",
    lastMessageAt: "2026-10-06T12:27:00Z",
    relativeTime: "5m",
    unreadCount: 1,
    startedAt: "6 minutes ago",
    messages: [
      {
        id: "msg-100",
        conversationId: "conv-4a8c",
        sender: "ai",
        senderName: "Super friendly Agent",
        text: "Hello from this super friendly agent 😊",
        createdAt: "6 minutes ago",
      },
      {
        id: "msg-101",
        conversationId: "conv-4a8c",
        sender: "visitor",
        senderName: "Visitor 4a8c",
        text: "How do I reset my password?",
        createdAt: "6 minutes ago",
      },
      {
        id: "msg-102",
        conversationId: "conv-4a8c",
        sender: "ai",
        senderName: "Super friendly Agent",
        text: "Go to acme.example/login and click Forgot password. Enter the email address you used to sign up, then open the reset email and click its link.\n\nThe email arrives within 5 minutes—check spam if needed. The link is valid for 1 hour, and your new password must be at least 10 characters.",
        createdAt: "6 minutes ago",
        citation: {
          documentName: "account-help.md",
          similarity: 0.70,
        },
        aiReasoning: {
          classification: "SUPPORT_QUESTION",
          classificationLabel: "Support question",
          statusBadge: "Answered from the knowledge base",
          thresholdNote: "The best match needs 0.50 for the agent to answer, and others from 0.40 join it.",
          bestMatchThreshold: 0.50,
          secondaryThreshold: 0.40,
          retrievedChunks: [
            {
              documentName: "account-help.md",
              similarity: 0.70,
              status: "USED",
              excerpt: "To reset password: visit /login, click Forgot password, enter registered email, and verify within 60 minutes.",
            },
            {
              documentName: "account-help.md",
              similarity: 0.59,
              status: "USED",
              excerpt: "Passwords must be at least 10 characters and contain letters and numbers.",
            },
            {
              documentName: "Plans and pricing",
              similarity: 0.29,
              status: "BELOW_THRESHOLD",
              excerpt: "Enterprise subscriptions include SAML 2.0 / OIDC single sign-on.",
            },
            {
              documentName: "opening-hours.md",
              similarity: 0.23,
              status: "BELOW_THRESHOLD",
              excerpt: "Live human support available Monday to Friday from 9 AM to 6 PM CET.",
            },
            {
              documentName: "refund-policy.pdf",
              similarity: 0.23,
              status: "BELOW_THRESHOLD",
              excerpt: "Subscriptions are billed monthly with a 14-day refund grace period.",
            },
          ],
          modelsUsed: "gpt-5-4-nano, gpt-5-6-terra",
          latencyFirstWordMs: 2900,
          latencyTotalSeconds: 3.6,
          tokensIn: 1081,
          tokensOut: 84,
        },
      },
    ],
  },
  {
    id: "conv-305a",
    visitor: {
      id: "vis-305a",
      name: "Visitor 305a",
      handle: "Visitor 305a",
      avatarSeed: "305a",
      avatarExpression: "happy",
      isOnline: true,
      email: "visitor305a@example.com",
      location: "United States",
      localTime: "03:25 local time",
      language: "American English",
      device: "Desktop",
      browser: "Chrome",
      os: "Windows 11",
      currentPage: "localhost:3000/docs",
      cameFrom: "Direct visit",
      firstSeen: "12 minutes ago",
      lastSeen: "5 minutes ago",
      visitsCount: 2,
    },
    status: "WAITING_HUMAN",
    handoffReason: "The visitor asked for a person",
    lastMessageSnippet: "Can I talk to a real person?",
    lastMessageAt: "2026-10-06T12:22:00Z",
    relativeTime: "5m",
    unreadCount: 1,
    startedAt: "10 minutes ago",
    messages: [
      {
        id: "msg-201",
        conversationId: "conv-305a",
        sender: "visitor",
        senderName: "Visitor 305a",
        text: "Can I talk to a real person?",
        createdAt: "5 minutes ago",
      },
      {
        id: "msg-202",
        conversationId: "conv-305a",
        sender: "system",
        senderName: "System",
        text: "Visitor clicked 'Talk to Human'. The conversation was routed to the operator queue.",
        createdAt: "5 minutes ago",
      },
    ],
  },
  {
    id: "conv-2634",
    visitor: {
      id: "vis-2634",
      name: "Visitor 2634",
      handle: "Visitor 2634",
      avatarSeed: "2634",
      avatarExpression: "curious",
      isOnline: true,
      location: "San Francisco, US",
      localTime: "03:22 local time",
      language: "American English",
      device: "Desktop",
      browser: "Safari",
      os: "macOS 15.0",
      currentPage: "localhost:3000/integrations",
      cameFrom: "Google Search",
      firstSeen: "20 minutes ago",
      lastSeen: "5 minutes ago",
      visitsCount: 1,
    },
    status: "WAITING_HUMAN",
    handoffReason: "The knowledge base doesn't cover this",
    lastMessageSnippet: "Do you integrate with Salesforce?",
    lastMessageAt: "2026-10-06T12:20:00Z",
    relativeTime: "5m",
    unreadCount: 1,
    startedAt: "15 minutes ago",
    messages: [
      {
        id: "msg-301",
        conversationId: "conv-2634",
        sender: "visitor",
        senderName: "Visitor 2634",
        text: "Do you integrate with Salesforce?",
        createdAt: "5 minutes ago",
      },
      {
        id: "msg-302",
        conversationId: "conv-2634",
        sender: "system",
        senderName: "System",
        text: "Top vector similarity was 0.38 (threshold 0.50). The knowledge base does not cover Salesforce integration. Guardrail auto-transferred to operator.",
        createdAt: "5 minutes ago",
      },
    ],
  },
  {
    id: "conv-8bab",
    visitor: {
      id: "vis-8bab",
      name: "Visitor 8bab",
      handle: "Visitor 8bab",
      avatarSeed: "8bab",
      avatarExpression: "heart",
      isOnline: true,
      location: "Toronto, Canada",
      localTime: "06:21 local time",
      language: "American English",
      device: "Mobile",
      browser: "Mobile Safari",
      os: "iOS 18.0",
      currentPage: "localhost:3000/support",
      cameFrom: "Direct visit",
      firstSeen: "1 hour ago",
      lastSeen: "6 minutes ago",
      visitsCount: 3,
    },
    status: "WAITING_HUMAN",
    handoffReason: "The visitor asked for a person",
    lastMessageSnippet: "Can I talk to a real person?",
    lastMessageAt: "2026-10-06T12:19:00Z",
    relativeTime: "6m",
    unreadCount: 1,
    startedAt: "1 hour ago",
    messages: [
      {
        id: "msg-401",
        conversationId: "conv-8bab",
        sender: "visitor",
        senderName: "Visitor 8bab",
        text: "Can I talk to a real person?",
        createdAt: "6 minutes ago",
      },
    ],
  },
  {
    id: "conv-7440",
    visitor: {
      id: "vis-7440",
      name: "Visitor 7440",
      handle: "Visitor 7440",
      avatarSeed: "7440",
      avatarExpression: "happy",
      isOnline: true,
      location: "Austin, US",
      localTime: "05:18 local time",
      language: "American English",
      device: "Desktop",
      browser: "Chrome",
      os: "Windows 11",
      currentPage: "localhost:3000/api",
      cameFrom: "GitHub",
      firstSeen: "2 hours ago",
      lastSeen: "6 minutes ago",
      visitsCount: 2,
    },
    status: "WAITING_HUMAN",
    handoffReason: "The knowledge base doesn't cover this",
    lastMessageSnippet: "Do you integrate with Salesforce?",
    lastMessageAt: "2026-10-06T12:18:00Z",
    relativeTime: "6m",
    unreadCount: 1,
    startedAt: "2 hours ago",
    messages: [
      {
        id: "msg-501",
        conversationId: "conv-7440",
        sender: "visitor",
        senderName: "Visitor 7440",
        text: "Do you integrate with Salesforce?",
        createdAt: "6 minutes ago",
      },
    ],
  },
  {
    id: "conv-161d",
    visitor: {
      id: "vis-161d",
      name: "Visitor 161d",
      handle: "Visitor 161d",
      avatarSeed: "161d",
      avatarExpression: "relaxed",
      isOnline: false,
      location: "Munich, Germany",
      localTime: "12:15 local time",
      language: "German",
      device: "Desktop",
      browser: "Firefox",
      os: "Linux",
      currentPage: "localhost:3000/download",
      cameFrom: "Product Hunt",
      firstSeen: "30 minutes ago",
      lastSeen: "6 minutes ago",
      visitsCount: 1,
    },
    status: "WAITING_HUMAN",
    handoffReason: "The agent wasn't sure of the answer",
    lastMessageSnippet: "Is there a mobile app?",
    lastMessageAt: "2026-10-06T12:15:00Z",
    relativeTime: "6m",
    unreadCount: 1,
    startedAt: "30 minutes ago",
    messages: [
      {
        id: "msg-601",
        conversationId: "conv-161d",
        sender: "visitor",
        senderName: "Visitor 161d",
        text: "Is there a mobile app?",
        createdAt: "6 minutes ago",
      },
    ],
  },
  {
    id: "conv-0ae2",
    visitor: {
      id: "vis-0ae2",
      name: "Visitor 0ae2",
      handle: "Visitor 0ae2",
      avatarSeed: "0ae2",
      avatarExpression: "happy",
      isOnline: true,
      location: "Sydney, Australia",
      localTime: "21:14 local time",
      language: "English",
      device: "Desktop",
      browser: "Edge",
      os: "Windows 10",
      currentPage: "localhost:3000/contact",
      cameFrom: "Direct visit",
      firstSeen: "45 minutes ago",
      lastSeen: "6 minutes ago",
      visitsCount: 1,
    },
    status: "WAITING_HUMAN",
    handoffReason: "The agent wasn't sure of the answer",
    lastMessageSnippet: "Do you offer phone support?",
    lastMessageAt: "2026-10-06T12:14:00Z",
    relativeTime: "6m",
    unreadCount: 1,
    startedAt: "45 minutes ago",
    messages: [
      {
        id: "msg-701",
        conversationId: "conv-0ae2",
        sender: "visitor",
        senderName: "Visitor 0ae2",
        text: "Do you offer phone support?",
        createdAt: "6 minutes ago",
      },
    ],
  },
  {
    id: "conv-cf46",
    visitor: {
      id: "vis-cf46",
      name: "Visitor cf46",
      handle: "Visitor cf46",
      avatarSeed: "cf46",
      avatarExpression: "relaxed",
      isOnline: true,
      location: "Stockholm, Sweden",
      localTime: "12:12 local time",
      language: "English",
      device: "Desktop",
      browser: "Chrome",
      os: "macOS",
      currentPage: "localhost:3000/returns",
      cameFrom: "Direct visit",
      firstSeen: "10 minutes ago",
      lastSeen: "6 minutes ago",
      visitsCount: 1,
    },
    status: "AI_ANSWERING",
    lastMessageSnippet: "Sorry, returns are eligible for a full refund...",
    lastMessageAt: "2026-10-06T12:12:00Z",
    relativeTime: "6m",
    startedAt: "10 minutes ago",
    messages: [
      {
        id: "msg-801",
        conversationId: "conv-cf46",
        sender: "visitor",
        senderName: "Visitor cf46",
        text: "What is your refund policy?",
        createdAt: "6 minutes ago",
      },
      {
        id: "msg-802",
        conversationId: "conv-cf46",
        sender: "ai",
        senderName: "Agent",
        text: "Sorry, returns are eligible for a full refund within 14 days of purchase. Just submit your receipt in the billing settings.",
        createdAt: "6 minutes ago",
      },
    ],
  },
  {
    id: "conv-a32a",
    visitor: {
      id: "vis-a32a",
      name: "Visitor a32a",
      handle: "Visitor a32a",
      avatarSeed: "a32a",
      avatarExpression: "relaxed",
      isOnline: false,
      location: "Vancouver, Canada",
      localTime: "03:10 local time",
      language: "English",
      device: "Desktop",
      browser: "Chrome",
      os: "macOS",
      currentPage: "localhost:3000/shipping",
      cameFrom: "Direct visit",
      firstSeen: "2 hours ago",
      lastSeen: "6 minutes ago",
      visitsCount: 1,
    },
    status: "AI_ANSWERING",
    lastMessageSnippet: "Yes, we ship to Canada. Delivery typically...",
    lastMessageAt: "2026-10-06T12:10:00Z",
    relativeTime: "6m",
    startedAt: "2 hours ago",
    messages: [
      {
        id: "msg-901",
        conversationId: "conv-a32a",
        sender: "visitor",
        senderName: "Visitor a32a",
        text: "Do you ship to Canada?",
        createdAt: "6 minutes ago",
      },
      {
        id: "msg-902",
        conversationId: "conv-a32a",
        sender: "ai",
        senderName: "Agent",
        text: "Yes, we ship to Canada. Delivery typically takes 3-5 business days via DHL Express.",
        createdAt: "6 minutes ago",
      },
    ],
  },
];
